version: '3.8'

services:
  bot:
    build: .
    container_name: renamer_telegram_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./downloads:/app/downloads
      - ./thumbnails:/app/thumbnails
